//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.07 at 05:16:07 PM CDT 
//


package com.bestbuy.eos.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="job" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="lastFireTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nextFireTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sql-query" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="params">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "job"
})
@XmlRootElement(name = "running-jobs")
public class RunningJobs {

    protected List<RunningJobs.Job> job;

    /**
     * Gets the value of the job property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the job property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJob().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RunningJobs.Job }
     * 
     * 
     */
    public List<RunningJobs.Job> getJob() {
        if (job == null) {
            job = new ArrayList<RunningJobs.Job>();
        }
        return this.job;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="lastFireTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nextFireTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sql-query" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="params">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lastFireTime",
        "nextFireTime",
        "sqlQuery",
        "params"
    })
    public static class Job {

        @XmlElement(required = true)
        protected String lastFireTime;
        @XmlElement(required = true)
        protected String nextFireTime;
        @XmlElement(name = "sql-query", required = true)
        protected String sqlQuery;
        @XmlElement(required = true)
        protected RunningJobs.Job.Params params;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the lastFireTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastFireTime() {
            return lastFireTime;
        }

        /**
         * Sets the value of the lastFireTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastFireTime(String value) {
            this.lastFireTime = value;
        }

        /**
         * Gets the value of the nextFireTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNextFireTime() {
            return nextFireTime;
        }

        /**
         * Sets the value of the nextFireTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNextFireTime(String value) {
            this.nextFireTime = value;
        }

        /**
         * Gets the value of the sqlQuery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSqlQuery() {
            return sqlQuery;
        }

        /**
         * Sets the value of the sqlQuery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSqlQuery(String value) {
            this.sqlQuery = value;
        }

        /**
         * Gets the value of the params property.
         * 
         * @return
         *     possible object is
         *     {@link RunningJobs.Job.Params }
         *     
         */
        public RunningJobs.Job.Params getParams() {
            return params;
        }

        /**
         * Sets the value of the params property.
         * 
         * @param value
         *     allowed object is
         *     {@link RunningJobs.Job.Params }
         *     
         */
        public void setParams(RunningJobs.Job.Params value) {
            this.params = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "param"
        })
        public static class Params {

            protected List<String> param;

            /**
             * Gets the value of the param property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the param property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getParam() {
                if (param == null) {
                    param = new ArrayList<String>();
                }
                return this.param;
            }
            public void setParam(List<String> params) {              
              this.param = params;
          }

        }

    }

}
